package workspace

import (
	"context"
	"crypto/sha256"
	"errors"
	"slices"
	"time"
)

const (
	maximumEditFiles       = 257
	maximumDotenvBytes     = int64(1 << 20)
	maximumTransactionTime = 5 * time.Minute
)

var (
	// ErrWorkspaceBusy reports that another preview, edit, inventory, or run
	// owns the single native workspace lease.
	ErrWorkspaceBusy = errors.New("native workspace is busy")
	// ErrRecoveryRequired reports a durable interrupted native-file edit. No
	// managed access may continue until an administrator resolves it.
	ErrRecoveryRequired = errors.New("native workspace edit requires recovery")
	// ErrSourceChanged reports that content, metadata, path identity, or the
	// candidate reference set changed after review.
	ErrSourceChanged = errors.New("native workspace source changed")
	// ErrInvalidEdit reports an internally invalid or unsafe edit plan.
	ErrInvalidEdit = errors.New("native workspace edit is invalid")
	// ErrNoEditJournal reports the absence of an interrupted edit.
	ErrNoEditJournal = errors.New("native workspace edit journal is empty")
)

// Purpose identifies the bounded activity serialized by Coordinator.
type Purpose string

const (
	PurposeRead      Purpose = "configuration_read"
	PurposePreview   Purpose = "configuration_preview"
	PurposeSave      Purpose = "configuration_save"
	PurposeInventory Purpose = "inventory"
	PurposeManualRun Purpose = "manual_run"
	PurposeScheduled Purpose = "scheduled_run"
	PurposeRecovery  Purpose = "recovery"
)

// FileIdentity is secret-free Linux inode and metadata evidence. It is safe
// for the recovery journal; it deliberately contains no content digest.
type FileIdentity struct {
	Exists     bool
	Device     uint64
	Inode      uint64
	Mode       uint32
	UID        uint32
	GID        uint32
	NLink      uint64
	Size       int64
	ModifiedAt time.Time
	ChangedAt  time.Time
}

// SourceFingerprint combines exact file content with metadata for live
// concurrent-change detection. SHA256 is never persisted by workspace.
type SourceFingerprint struct {
	Path     string
	Identity FileIdentity
	SHA256   [sha256.Size]byte
}

// SourceFile is one bounded native source retained only for the caller's
// current operation. Content is never stored by workspace.
type SourceFile struct {
	Role        PathRole
	Path        string
	Reference   string
	Content     []byte
	Fingerprint SourceFingerprint
}

// SourceSet is an exact, verified YAML and dotenv snapshot. Close clears its
// confidential buffers and callers must not use it afterward.
type SourceSet struct {
	Selection     Selection
	Configuration SourceFile
	Dotenv        []SourceFile
	closed        bool
}

// Close clears all source bytes. It is idempotent.
func (sources *SourceSet) Close() {
	if sources == nil || sources.closed {
		return
	}
	clear(sources.Configuration.Content)
	sources.Configuration.Content = nil
	sources.Configuration.Fingerprint = SourceFingerprint{}
	for index := range sources.Dotenv {
		clear(sources.Dotenv[index].Content)
		sources.Dotenv[index].Content = nil
		sources.Dotenv[index].Fingerprint = SourceFingerprint{}
	}
	sources.closed = true
}

// Files returns shallow metadata copies in stable configuration-then-dotenv
// order. Confidential Content slices still refer to SourceSet and are cleared
// by Close.
func (sources *SourceSet) Files() []SourceFile {
	if sources == nil || sources.closed {
		return nil
	}
	files := make([]SourceFile, 0, 1+len(sources.Dotenv))
	files = append(files, sources.Configuration)
	files = append(files, sources.Dotenv...)
	return files
}

// Replacement is one exact active native file generated by nativeconfig.
// Only RoleConfiguration and candidate-referenced RoleDotenv paths are valid.
type Replacement struct {
	Role    PathRole
	Path    string
	Content []byte
}

// CommitPlan binds replacements to the exact SourceSet and complete candidate
// YAML that was previewed and validated by nativeconfig.
type CommitPlan struct {
	Sources                *SourceSet
	CandidateConfiguration []byte
	Replacements           []Replacement
}

// CandidatePath reports how a candidate native reference resolves. Missing
// dotenv targets are safe only when an exact replacement will create them.
type CandidatePath struct {
	Role       PathRole
	Reference  string
	Path       string
	Exists     bool
	WillCreate bool
	Evidence   PathEvidence
}

// CandidateAudit is bounded path evidence derived from candidate YAML before
// any native file is staged.
type CandidateAudit struct {
	Storage  PathEvidence
	Dotenv   []CandidatePath
	Webroots []PathEvidence
}

// CommitGuard revalidates the administrator session immediately before the
// first active rename. It must not mutate native files.
type CommitGuard func(context.Context) error

// FailurePoint identifies deterministic test injection boundaries.
type FailurePoint string

const (
	FailureAfterJournal       FailurePoint = "after_journal"
	FailureBeforeStageWrite   FailurePoint = "before_stage_write"
	FailureBeforeStageSync    FailurePoint = "before_stage_file_sync"
	FailureBeforeStageDirSync FailurePoint = "before_stage_directory_sync"
	FailureAfterStage         FailurePoint = "after_stage"
	FailureAfterPrepared      FailurePoint = "after_prepared"
	FailureBeforeReplace      FailurePoint = "before_replace"
	FailureAfterRename        FailurePoint = "after_rename_before_placement_record"
	FailureAfterReplace       FailurePoint = "after_replace"
	FailureBeforeActiveSync   FailurePoint = "before_active_directory_sync"
	FailureAfterDirectorySync FailurePoint = "after_directory_sync"
	FailureAfterAppliedRecord FailurePoint = "after_applied_record"
	FailureBeforeOldUnlink    FailurePoint = "before_displaced_unlink"
	FailureAfterCleanupRename FailurePoint = "after_cleanup_quarantine_rename"
	FailureAfterCleanupScrub  FailurePoint = "after_cleanup_scrub"
	FailureAfterCleanupUnlink FailurePoint = "after_cleanup_unlink"
	FailureBeforeOldDirSync   FailurePoint = "before_displaced_directory_sync"
	FailureBeforeFinalize     FailurePoint = "before_finalize"
)

// FailureInjector is used only to make filesystem and crash boundaries
// deterministic in tests. Production callers omit it.
type FailureInjector func(FailurePoint, int) error

// TransactionOption configures a TransactionManager.
type TransactionOption func(*transactionOptions) error

type transactionOptions struct {
	now      func() time.Time
	injector FailureInjector
	timeout  time.Duration
}

// WithTransactionTimeout narrows the manager-owned maximum duration. It is
// primarily useful for deterministic tests; production uses the fixed five
// minute upper bound.
func WithTransactionTimeout(timeout time.Duration) TransactionOption {
	return func(options *transactionOptions) error {
		if timeout <= 0 || timeout > maximumTransactionTime {
			return errors.New("native edit transaction timeout is invalid")
		}
		options.timeout = timeout
		return nil
	}
}

// WithTransactionClock supplies a controllable UTC clock for tests.
func WithTransactionClock(now func() time.Time) TransactionOption {
	return func(options *transactionOptions) error {
		if now == nil {
			return errors.New("native edit clock is required")
		}
		options.now = now
		return nil
	}
}

// WithFailureInjector supplies deterministic failure boundaries for tests.
func WithFailureInjector(injector FailureInjector) TransactionOption {
	return func(options *transactionOptions) error {
		if injector == nil {
			return errors.New("native edit failure injector is required")
		}
		options.injector = injector
		return nil
	}
}

// JournalPhase is a durable, secret-free edit phase.
type JournalPhase string

const (
	JournalStaging    JournalPhase = "staging"
	JournalPrepared   JournalPhase = "prepared"
	JournalReplacing  JournalPhase = "replacing"
	JournalFinalizing JournalPhase = "finalizing"
)

// Journal contains only recovery metadata. It never contains native bytes,
// content digests, field identifiers, summaries, or secret values.
type Journal struct {
	TransactionID     string
	Phase             JournalPhase
	WorkingDirectory  string
	ConfigurationPath string
	CreatedAt         time.Time
	Files             []JournalFile
}

// JournalFile is one target's persisted replacement identity.
type JournalFile struct {
	Ordinal        int
	Role           PathRole
	TargetPath     string
	ParentPath     string
	StageBasename  string
	Original       FileIdentity
	Parent         FileIdentity
	CandidateReady bool
	Candidate      FileIdentity
	Applied        bool
}

// RecoveryState summarizes a journal without replaying it.
type RecoveryState string

const (
	RecoveryUnapplied RecoveryState = "unapplied"
	RecoveryPartial   RecoveryState = "partial"
	RecoveryApplied   RecoveryState = "applied"
	RecoveryAmbiguous RecoveryState = "ambiguous"
)

// RecoveryFileState classifies only inode/metadata placement, never content.
type RecoveryFileState string

const (
	RecoveryFileUnstaged  RecoveryFileState = "unstaged"
	RecoveryFileUnapplied RecoveryFileState = "unapplied"
	RecoveryFileApplied   RecoveryFileState = "applied"
	RecoveryFileAmbiguous RecoveryFileState = "ambiguous"
)

// Recovery is a fresh secret-free classification of a durable journal.
type Recovery struct {
	TransactionID     string
	WorkingDirectory  string
	ConfigurationPath string
	Phase             JournalPhase
	State             RecoveryState
	Files             []RecoveryFile
}

// RecoveryFile is one classified target.
type RecoveryFile struct {
	Ordinal int
	Role    PathRole
	Path    string
	State   RecoveryFileState
}

// RecoveryResolution is an explicit administrator-directed outcome. None of
// these options replays an unapplied candidate.
type RecoveryResolution string

const (
	ResolutionDiscardUnapplied RecoveryResolution = "discard_unapplied"
	ResolutionFinalizeApplied  RecoveryResolution = "finalize_applied"
	ResolutionAdoptCurrent     RecoveryResolution = "adopt_current"
)

// RecoveryValidator validates the freshly read active file set before an
// applied or repaired current set can be accepted.
type RecoveryValidator func(context.Context, *SourceSet) error

func cloneReplacement(value Replacement) Replacement {
	value.Content = slices.Clone(value.Content)
	return value
}
